name: Build and push

on:
  push:
    tags:
      - "*/*/*.*.*"

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: docker
    steps:
      - name: Build and push image
        uses: https://git.dev.armlab.pro/armor/sds-deploy/.gitea/actions/build-by-tag@main
        with:
          registry-url: ${{ vars.REGISTRY_URL }}
          checkout-token: ${{ secrets.GITEA_TOKEN }}
          yc-service-account-key-json: ${{ secrets.YC_SERVICE_ACCOUNT_KEY_JSON }}
