intTransport:
  server: api.armlab.pro:4222
  tls:
    crtFile: ./cert/tls.crt
    keyFile: ./cert/tls.key
    caFile: ./cert/ca.crt
extTransport:
  server: 0.0.0.0:4000
  secret:
    - TestSecretKey
smpp:
  endpoint: ["217.76.1.74:2775", "217.76.1.86:2775"]
  auth:
    user: SafeKids
    password: pass123
  address:
    sourceAddr: "1020"
  respTimeout: 30s

accountId: 923e0af7-8c92-4078-b9e5-0894d4efc4f8
catalogDir: catalog

vivaApi:
  baseURL: "https://viva.zsquare.ru/api/rest"
  userName: "ZsquareLLC"
  password: "KasperskySafeKids2026%&!"
